-- 创建库存表信息
CREATE TABLE `sys_stock_quantity` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`company` VARCHAR(100) NULL DEFAULT NULL COMMENT '公司名称',
	`materialcoding` VARCHAR(30) NULL DEFAULT NULL COMMENT '物料编码',
	`materialdescription` VARCHAR(100) NULL DEFAULT NULL COMMENT '物料描述',
	`erp` VARCHAR(50) NULL DEFAULT NULL COMMENT 'erp协议号',
	`projectname` VARCHAR(50) NULL DEFAULT NULL COMMENT '项目名称',
	`producttype` VARCHAR(50) NULL DEFAULT NULL COMMENT '产品类别',
	`componentdirection` VARCHAR(50) NULL DEFAULT NULL COMMENT '组件去向',
	`grade` VARCHAR(50) NULL DEFAULT NULL COMMENT '质量等级',
	`componentmodel` VARCHAR(50) NULL DEFAULT NULL COMMENT '组件型号',
	`componenttype` INT(11) NULL DEFAULT NULL COMMENT '组件类型',
	`watts` INT(11) NULL DEFAULT '0' COMMENT '瓦特',
	`boxfactory` VARCHAR(50) NULL DEFAULT NULL COMMENT '接线盒厂家',
	`batterycell` VARCHAR(50) NULL DEFAULT NULL COMMENT '电池片',
	`gatesnumber` VARCHAR(50) NULL DEFAULT NULL COMMENT '栅数',
	`currentfile` VARCHAR(50) NULL DEFAULT NULL COMMENT '电流档',
	`componentprocess` VARCHAR(50) NULL DEFAULT NULL COMMENT '组件工艺',
	`bordersize` VARCHAR(50) NULL DEFAULT NULL COMMENT '边框尺寸',
	`bordercolor` VARCHAR(50) NULL DEFAULT NULL COMMENT '边框颜色',
	`backplanetype` VARCHAR(50) NULL DEFAULT NULL COMMENT '背板类型',
	`backpanelcolor` VARCHAR(50) NULL DEFAULT NULL COMMENT '背板颜色',
	`junctionboxtype` VARCHAR(50) NULL DEFAULT NULL COMMENT '接线盒类型',
	`cellcolor` VARCHAR(50) NULL DEFAULT NULL COMMENT '电池片颜色',
	`linelength` VARCHAR(50) NULL DEFAULT NULL COMMENT '线长',
	`electricparameter` VARCHAR(50) NULL DEFAULT NULL COMMENT '电池参数',
	`currentparameter` VARCHAR(50) NULL DEFAULT NULL COMMENT '电流档参数',
	`transferitemname` VARCHAR(50) NULL DEFAULT NULL COMMENT '调货前名称',
	`reasonforfailure` VARCHAR(50) NULL DEFAULT NULL COMMENT '不合格原因',
	`reasonforlimitation` VARCHAR(50) NULL DEFAULT NULL COMMENT '限制原因',
	`releasecondition` VARCHAR(50) NULL DEFAULT NULL COMMENT '放行条件',
	`numberbesorted` INT(15) NULL DEFAULT '0' COMMENT '待拣数量',
	`isolatedquantity` INT(15) NULL DEFAULT '0' COMMENT '隔离数量',
	`unqualifiedquantity` INT(15) NULL DEFAULT '0' COMMENT '不合格数量',
	`conditionalrelease` INT(15) NULL DEFAULT '0' COMMENT '条件放行',
	`deliverablesnumber` INT(15) NULL DEFAULT '0' COMMENT '可发数量',
	`traynumber` VARCHAR(50) NULL DEFAULT NULL COMMENT '托盘号',
	`deliverycustomer` VARCHAR(50) NULL DEFAULT NULL COMMENT '发货客户',
	`outboundnumber` INT(20) NULL DEFAULT '0' COMMENT '发货数量',
	`storage_create` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '出库时间',
	`creator` BIGINT(20) NULL DEFAULT '0' COMMENT '创建者',
	`gmt_create` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
	`editor` BIGINT(20) NULL DEFAULT NULL COMMENT '更新者',
	`gmt_modified` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	`is_deleted` INT(11) NULL DEFAULT '0' COMMENT '数据状态:1:删除 0:未删除',
	`remarks` VARCHAR(120) NULL DEFAULT NULL COMMENT '备注',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1877
;